version: '3.8'

services:
  client:
    build:
      context: ./stroyximtorg.client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      
  server:
    build:
      context: ./StroyXimTorg.Server
      dockerfile: Dockerfile
    ports:
      - "5000:80" 
